// flow-typed signature: 5f061a99073e9efa0dea7b437e4637c5
// flow-typed version: <<STUB>>/fixpack_v~2.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fixpack/fixpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fixpack/fixpack.js' {
  declare module.exports: $Exports<'fixpack/fixpack'>;
}
